/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Police.PoliceOfficer;

import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GunViolenceCaseWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author joshiaditya
 */
public class GunViolenceCaseInvestigationJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    GunViolenceCaseWorkRequest request;
    Network network;
    UserAccount userAccount;
    /**
     * Creates new form GunViolenceCaseInvestigationJPanel
     */
    public GunViolenceCaseInvestigationJPanel(JPanel userProcessContainer, GunViolenceCaseWorkRequest request, UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.request = request;
        this.userAccount = userAccount;
        txtCaseID.setText(String.valueOf(request.getCaseID()));
        populateData();
    }
    
    public void populateData(){
        
        txtAddress.setText(request.getSuspectAddress());
        txtGangName.setText(request.getGangName());
        txtGunType.setText(request.getGunType());
        txtMotive.setText(request.getMotive());
        txtOfficerComments.setText(request.getOfficerComments());
        txtSuspectName.setText(request.getSuspectName());
        dob.setDate(request.getSuspectDateOfBirth());
        txtIncidentDate.setText(request.getIncidentOcuredDate().toString());
        
        if(request.isAssociatedWithGang() == true)
            btnGangYes.setSelected(true);
        if(request.isNotAssociatedWithGang() == true)
            btnGangNo.setSelected(true);
        
        if(request.isGunViolenceHistory() == true)
            btnHistoryYes.setSelected(true);
        if(request.isNoGunViolenceHistory() == true)
            btnHistoryNo.setSelected(true);
        
        if(request.isIsGunLegal() == true)
            btnYes.setSelected(true);
        if(request.isIsGunIllegal() == true)
            btnNo.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        legallyPurchased = new javax.swing.ButtonGroup();
        gunViolenceHistory = new javax.swing.ButtonGroup();
        gangAssociation = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtGunType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotive = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnHistoryYes = new javax.swing.JRadioButton();
        btnHistoryNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtCaseID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSuspectName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dob = new org.jdesktop.swingx.JXDatePicker();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtOfficerComments = new javax.swing.JTextArea();
        txtGangName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGangYes = new javax.swing.JRadioButton();
        btnGangNo = new javax.swing.JRadioButton();
        txtIncidentDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel1.setText("Gun Type:");

        jLabel2.setText("Is gun used in incident purchased legally?");

        legallyPurchased.add(btnYes);
        btnYes.setText("Yes");

        legallyPurchased.add(btnNo);
        btnNo.setText("No");

        jLabel3.setText("What was the motive behind gun violence?");

        txtMotive.setColumns(20);
        txtMotive.setRows(5);
        jScrollPane1.setViewportView(txtMotive);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Does suspect has history of gun violence cases?");

        gunViolenceHistory.add(btnHistoryYes);
        btnHistoryYes.setText("Yes");

        gunViolenceHistory.add(btnHistoryNo);
        btnHistoryNo.setText("No");

        jLabel5.setText("Case ID:");

        txtCaseID.setEnabled(false);

        jLabel6.setText("Name of Suspect");

        jLabel7.setText("Address of suspect:");

        jLabel8.setText("Suspect's Date of birth (DD/MM/YYYY):");

        jLabel15.setText("Is suspect associated with any group/gang?");

        jLabel16.setText("Name of Group associated if any:");

        jLabel17.setText("Observations/comments of Investaging Officer:");

        txtOfficerComments.setColumns(20);
        txtOfficerComments.setRows(5);
        jScrollPane5.setViewportView(txtOfficerComments);

        jLabel9.setText("Investigation Questionnaire");

        gangAssociation.add(btnGangYes);
        btnGangYes.setText("Yes");

        gangAssociation.add(btnGangNo);
        btnGangNo.setText("No");

        txtIncidentDate.setEnabled(false);

        jLabel10.setText("Incident Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel3))
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(txtGunType)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnHistoryYes)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnHistoryNo))
                                        .addComponent(txtAddress)
                                        .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGangName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGangYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGangNo))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(176, 176, 176)
                                            .addComponent(jLabel6))
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIncidentDate)
                                    .addComponent(txtSuspectName)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnYes)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNo)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCaseID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIncidentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSuspectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGunType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnYes)
                    .addComponent(btnNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistoryYes)
                    .addComponent(btnHistoryNo)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnGangYes)
                    .addComponent(btnGangNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtGangName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(123, 123, 123)))
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(request.getStatus().equals("Closed")){
            
            JOptionPane.showMessageDialog(this, "Cannot update a closed case!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            
            request.setSuspectName(txtSuspectName.getText().trim());
            request.setSuspectAddress(txtAddress.getText().trim());
            request.setGangName(txtGangName.getText());
            request.setOfficerComments(txtOfficerComments.getText().trim());
            request.setGunType(txtGunType.getText());
            request.setMotive(txtMotive.getText());
            
            if(btnYes.isSelected())
                request.setIsGunLegal(true);
            if(btnNo.isSelected())
                request.setIsGunIllegal(true);
            
            if(btnHistoryYes.isSelected())
                request.setGunViolenceHistory(true);
            if(btnHistoryNo.isSelected())
                request.setNoGunViolenceHistory(true);
            
            if(btnGangYes.isSelected())
                request.setAssociatedWithGang(true);
            if(btnGangNo.isSelected())
                request.setNotAssociatedWithGang(true);

            Date date = dob.getDate();
            if(date != null && date.before(new Date())){

                request.setSuspectDateOfBirth(date);
                JOptionPane.showMessageDialog(null, "Details Saved!!");
            }else if( date != null){
                dob.setDate(null);
                JOptionPane.showMessageDialog(null, "Invalid date input! All data except date saved!");
            } else {
                JOptionPane.showMessageDialog(null, "Details Saved!!");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnGangNo;
    private javax.swing.JRadioButton btnGangYes;
    private javax.swing.JRadioButton btnHistoryNo;
    private javax.swing.JRadioButton btnHistoryYes;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYes;
    private org.jdesktop.swingx.JXDatePicker dob;
    private javax.swing.ButtonGroup gangAssociation;
    private javax.swing.ButtonGroup gunViolenceHistory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.ButtonGroup legallyPurchased;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCaseID;
    private javax.swing.JTextField txtGangName;
    private javax.swing.JTextField txtGunType;
    private javax.swing.JTextField txtIncidentDate;
    private javax.swing.JTextArea txtMotive;
    private javax.swing.JTextArea txtOfficerComments;
    private javax.swing.JTextField txtSuspectName;
    // End of variables declaration//GEN-END:variables
}
