/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Police.PoliceOfficer;

import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CaseWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha Varshney
 */
public class ViewSelectedRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewSelectedRequestJPanel
     */
   JPanel userProcessContainer;
    CaseWorkRequest request;
    Network network;
    UserAccount userAccount;

    ViewSelectedRequestJPanel(JPanel userProcessContainer, CaseWorkRequest request, UserAccount userAccount, Network network) {
       initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.request = request;
        this.userAccount = userAccount;
        populateTable();
    }
    
    
    public void populateTable(){
        
         DefaultTableModel dtm = (DefaultTableModel) viewCasejTable.getModel();
        dtm.setRowCount(0);

        for (WorkRequest req : userAccount.getWorkQueue().getWorkRequestList()) {

            if (req instanceof CaseWorkRequest) {
                
                if(Integer.toString(((CaseWorkRequest) req).getCaseID()).equals(request.getCaseID())){

                CaseWorkRequest caseRequest = (CaseWorkRequest) req;
                Object[] row = new Object[6];
                row[0] = caseRequest;
                row[1] = caseRequest.getIncidentType();
                row[2] = caseRequest.getIncidentOcuredDate();
                row[3] = caseRequest.getTestResultDate();
                row[4] = caseRequest.getTestResult();
                row[5] = caseRequest.getStatus();

                dtm.addRow(row);

            }
            }

        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewCasejTable = new javax.swing.JTable();

        viewCasejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Case ID", "Incident Type", "Incident Occured Date", "Test Report Date", "Test Result", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewCasejTable);
        if (viewCasejTable.getColumnModel().getColumnCount() > 0) {
            viewCasejTable.getColumnModel().getColumn(0).setResizable(false);
            viewCasejTable.getColumnModel().getColumn(1).setResizable(false);
            viewCasejTable.getColumnModel().getColumn(2).setResizable(false);
            viewCasejTable.getColumnModel().getColumn(3).setResizable(false);
            viewCasejTable.getColumnModel().getColumn(4).setResizable(false);
            viewCasejTable.getColumnModel().getColumn(5).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewCasejTable;
    // End of variables declaration//GEN-END:variables
}
