/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Analysis;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CaseWorkRequest;
import Business.WorkQueue.GunViolenceCaseWorkRequest;
import Business.WorkQueue.RobberyCaseWorkRequest;
import Business.WorkQueue.SubstanceAbuseCaseWorkRequest;
import Business.WorkQueue.WorkRequest;
import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.HeaderFooter;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfTemplate;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.CardLayout;
import java.awt.Graphics2D;
import java.io.FileOutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sneha
 */
public class AnalysisByArea extends javax.swing.JPanel {

    /**
     * Creates new form AnalysisByArea
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;

    public AnalysisByArea(JPanel userProcessContainer, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;

        populateTable();

    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) areaTable.getModel();
        model.setRowCount(0);
        int incidentCount = 0;
        ArrayList<String> zipcodes = new ArrayList<>();
        Set<String> hs = new HashSet<>();
        Map<String, ArrayList<String>> crimeCountMap = new HashMap<String, ArrayList<String>>();
        ArrayList<String> incidentTypes = new ArrayList<>();

        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                for (WorkRequest req : ua.getWorkQueue().getWorkRequestList()) {

                    String zip = ((CaseWorkRequest) req).getZipCode();
                    zipcodes.add(zip);
                }
            }
        }
        hs.addAll(zipcodes);
        zipcodes.clear();
        zipcodes.addAll(hs);

        for (int hashvalue = 0; hashvalue < zipcodes.size(); hashvalue++) {
            String zip1 = null;
            int gunCount = 0;
            int substanceCount = 0;
            int robberyCount = 0;

            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                    for (WorkRequest req : ua.getWorkQueue().getWorkRequestList()) {
                        zip1 = ((CaseWorkRequest) req).getZipCode();
                        if (zipcodes.get(hashvalue).equals(zip1)) {
                            if (req instanceof GunViolenceCaseWorkRequest) {
                                gunCount++;
                            } else if (req instanceof RobberyCaseWorkRequest) {
                                robberyCount++;
                            } else if (req instanceof SubstanceAbuseCaseWorkRequest) {
                                substanceCount++;
                            }
                        }
                    }
                }
            }

            Object[] row = new Object[4];
            row[0] = zipcodes.get(hashvalue);
            row[1] = gunCount;
            row[2] = robberyCount;
            row[3] = substanceCount;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        headerlbl = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        areaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Zipcode", "Gun Voilence", "Substance Abuse", "Robbery"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(areaTable);

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Create a PDF report");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        headerlbl.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        headerlbl.setText("INCIDENT REPORT PER ZIP CODE PER EVENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(106, 106, 106))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Document document = new Document();
        boolean shapes = true;
        if (Paths.get(System.getProperty("user.dir") + "/IncidentReport.pdf") != null) {
            Path path = Paths.get(System.getProperty("user.dir") + "/IncidentReport.pdf");
            path.toFile().delete();
        }
        try {
            PdfWriter writer;
            Phrase phrase1 = new Phrase("INCIDENT REPORT PER ZIP CODE PER EVENT: ", FontFactory.getFont(FontFactory.TIMES_ROMAN, 28, Font.NORMAL));

            if (shapes) {
                writer = PdfWriter.getInstance(document,
                        new FileOutputStream("IncidentReport.pdf"));
            } else {
                writer = PdfWriter.getInstance(document,
                        new FileOutputStream("IncidentReport.pdf"));
            }
            document.open();
            HeaderFooter header = new HeaderFooter(phrase1, true);
            document.setHeader(header);
            PdfContentByte cb = writer.getDirectContent();
            PdfTemplate tp = cb.createTemplate(1000, 1000);
            PdfTemplate tp1 = cb.createTemplate(1000, 1000);
            Graphics2D g2;
            if (shapes) {
                g2 = tp.createGraphicsShapes(500, 500);
            } else {
                g2 = tp.createGraphics(500, 500);
            }
            //document.close();
            Graphics2D g3;
            if (shapes) {
                g3 = tp1.createGraphicsShapes(500, 500);
            } else {
                g3 = tp1.createGraphics(500, 500);

            }
            // shapes=true;
            headerlbl.print(g3);

            areaTable.print(g2);
            g2.dispose();
            cb.addTemplate(tp1, 30, 150);
            g3.dispose();
            cb.addTemplate(tp, 30, 300);
            document.close();
            JOptionPane.showMessageDialog(null, "Report generated succesfully");
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }


    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable areaTable;
    private javax.swing.JLabel headerlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
